site_name: AUDIT - Analysis & Evaluation Dashboard of Artificial Intelligence
site_url: https://caumente.github.io/AUDIT/
theme:
  name: material
  logo: assets/lupa2.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - AUDIT library: index.md
  - Getting started: Getting_started/getting_started.md
  - API reference:
    - Feature extractor:
      - Feature extractor: API_reference/features/feature_extractor.md
      - Statistical features: API_reference/features/statistical.md
      - Texture features: API_reference/features/texture.md
      - Tumor features: API_reference/features/tumor.md
      - Spatial features: API_reference/features/spatial.md
    - Metric extractor:
      - Metric extractor: API_reference/metrics/metric_extractor.md
      - Custom metrics: API_reference/metrics/custom_metrics.md
    - Utils:
      - Utils: API_reference/utils/utils.md
      - Sequences: API_reference/utils/sequences.md
      - File manager: API_reference/utils/file_manager.md
  - Dashboard:
    - Home page: app/APP.md
    - Univariate page: app/univariate.md
    - Multivariate page: app/multivariate.md
  - Tutorials:
      - Postprocess predictions: tutorials/postprocess_outputs.md
      - Others: tutorials/tutorials.md
  - About:
    - License: about/LICENSE.md
    - Release Notes: about/release-notes.md

plugins:
  - social
  - search
#  - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/caumente/AUDIT

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/caumente"  target="_blank" rel="noopener">Carlos Aumente Maestro</a>