site_name: AUDIT - Analysis & Evaluation Dashboard of Artificial Intelligence
site_url: https://caumente.github.io/AUDIT/
site_description: "Documentation for AUDIT — an open-source tool to evaluate medical image segmentation models."
#repo_name: caumente/AUDIT
#repo_url: https://github.com/caumente/AUDIT

theme:
  name: material
  logo: assets/lupa2.png
  favicon: assets/favicon.ico
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.follow
#    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - AUDIT library: index.md
  - Getting started: getting_started/getting_started.md
  - API reference:
    - Feature extraction:
      - API_reference/features/index.md
      - Statistical features: API_reference/features/statistical.md
      - Texture features: API_reference/features/texture.md
      - Tumor features: API_reference/features/tumor.md
      - Spatial features: API_reference/features/spatial.md
    - Metric extraction:
      - Metric extraction: API_reference/metrics/metric_extraction.md
      - Audit metrics: API_reference/metrics/audit_metrics.md
    - Utils:
      - Sequences: API_reference/utils/sequences.md
      - File manager: API_reference/utils/file_manager.md
  - Analysis modes:
    - Home page: analysis_modes/home_page.md
    - Univariate: analysis_modes/univariate.md
    - Multivariate: analysis_modes/multivariate.md
    - Segmentation error matrix: analysis_modes/segmentation_error.md
    - Single model performance: analysis_modes/single_model.md
    - Pairwise model performance: analysis_modes/pairwise_model.md
    - Multi-model performance: analysis_modes/multi_model.md
    - Longitudinal: analysis_modes/longitudinal.md
    - Subjects' exploration: analysis_modes/subjects_exploration.md

  - Tutorials:
      - Preprocessing dataset: tutorials/preprocessing.md
      - Postprocessing segmentations: tutorials/postprocessing_segmentations.md
  - About:
    - License: about/LICENSE.md
    - Release notes: about/release-notes.md

plugins:
  - social
  - search
#  - mkdocstrings
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/caumente/AUDIT
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@AUDITapp
  consent:
    title: Cookie consent
    description: >-
      We use cookies to improve your user experience and help us enhance the AUDIT documentation and tools. By 
      consenting, you support us in making AUDIT better for everyone.
  analytics:
    provider: google
    property: G-9LHEEH0JK9
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-sad-outline
          name: Not helpful at all
          data: 1
          note: >-
            Thanks for your feedback! Please help us improve by
            filling out <a href="https://forms.gle/WDezrbJiaJkpGDLMA" target="_blank" rel="noopener">this feedback form</a>.
        - icon: material/emoticon-sad
          name: Not very helpful
          data: 2
          note: >-
            Thanks for your feedback! Please help us improve by
            filling out <a href="https://forms.gle/WDezrbJiaJkpGDLMA" target="_blank" rel="noopener">this feedback form</a>.
        - icon: material/emoticon-neutral-outline
          name: Neutral
          data: 3
          note: >-
            Thanks for your feedback! Please help us improve by
            filling out <a href="https://forms.gle/WDezrbJiaJkpGDLMA" target="_blank" rel="noopener">this feedback form</a>.
        - icon: material/emoticon-happy
          name: Helpful
          data: 4
          note: >-
            Thanks for your feedback! Please help us improve by
            filling out <a href="https://forms.gle/WDezrbJiaJkpGDLMA" target="_blank" rel="noopener">this feedback form</a>.
        - icon: material/emoticon-happy-outline
          name: Very helpful
          data: 5
          note: >-
            Thanks for your feedback! Please help us improve by
            filling out <a href="https://forms.gle/WDezrbJiaJkpGDLMA" target="_blank" rel="noopener">this feedback form</a>.
  generator: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


copyright: |
  &copy; Copyright 2025, Carlos Aumente-Maestro <br>
  <a href="#__consent">Change cookie settings</a>