site_name: AUDIT - Analysis & Evaluation Dashboard of Artificial Intelligence
site_url: https://caumente.github.io/AUDIT/

nav:
  - Home: index.md
  - User Guide:
    - Feature extractor: user-guide/feature-extractor.md
    - Metric extractor: user-guide/metric-extractor.md
    - Utils: user-guide/utils.md
  - Dashboard: APP.md
  - Tutorials:
      - Postprocess predictions: tutorials/postprocess_outputs.md
      - Others: tutorials/tutorials.md
  - About:
    - License: about/LICENSE.md
    - Release Notes: about/release-notes.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - social
  - search
  - mkdocstrings


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/caumente/AUDIT
#    - icon: fontawesome/brands/twitter
#      link:
#    - icon: fontawesome/brands/linkedin
#      link:

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/caumente"  target="_blank" rel="noopener">Carlos Aumente Maestro</a>