site_name: AUDIT - Analysis & Evaluation Dashboard of Artificial Intelligence
site_url: https://caumente.github.io/AUDIT/
theme:
  name: material
  logo: assets/lupa2.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - AUDIT library: index.md
  - Getting started: getting_started/getting_started.md
  - API reference:
    - Feature extraction:
      - Feature extraction: API_reference/features/feature_extraction.md
      - Statistical features: API_reference/features/statistical.md
      - Texture features: API_reference/features/texture.md
      - Tumor features: API_reference/features/tumor.md
      - Spatial features: API_reference/features/spatial.md
    - Metric extraction:
      - Metric extraction: API_reference/metrics/metric_extraction.md
      - Audit metrics: API_reference/metrics/audit_metrics.md
    - Utils:
      - Sequences: API_reference/utils/sequences.md
      - File manager: API_reference/utils/file_manager.md
  - Analysis modes:
    - Home page: app/home_page.md
    - Univariate: app/univariate.md
    - Multivariate: app/multivariate.md
    - Segmentation error matrix: app/segmentation_error.md
    - Single model performance: app/single_model.md
    - Pairwise model performance: app/pairwise_model.md
    - Multi-model performance: app/multi_model.md
    - Longitudinal: app/longitudinal.md
    - Subjects' exploration: app/subjects_exploration.md

  - Tutorials:
      - Preprocessing dataset: tutorials/preprocessing.md
      - Postprocessing segmentations: tutorials/postprocessing_segmentations.md
  - About:
    - License: about/LICENSE.md
    - Release notes: about/release-notes.md

plugins:
  - social
  - search
#  - mkdocstrings
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/caumente/AUDIT

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/caumente"  target="_blank" rel="noopener">Carlos Aumente Maestro</a>