labels:
  BKG: 0
  EDE: 4
  ENH: 1
  NEC: 2
datasets_root_path: '/home/carlos/Documentos/proyectos/AUDIT/datasets/brats2020'
csv_features_path: '/home/carlos/Documentos/proyectos/AUDIT/outputs'
features_analysis:
  data_paths:
    NW: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_NW.csv'
    UCSF: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_UCSF.csv'
    BRATS: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_BRATS.csv'

distributions_analysis:
  data_paths:
    NW: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_NW.csv'
    UCSF: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_UCSF.csv'
    BRATS: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_BRATS.csv'

segmentation_error_analysis:
  NW:
    ground_truth: '/home/carlos/Documentos/proyectos/AUDIT/datasets/nw/nw_images'
    mvp_1: '/home/carlos/Documentos/proyectos/AUDIT/datasets/nw/nw_seg/nw_mvp_1'
    mvp_2: '/home/carlos/Documentos/proyectos/AUDIT/datasets/nw/nw_seg/nw_mvp_2'
    mvp_2.3: '/home/carlos/Documentos/proyectos/AUDIT/datasets/nw/nw_seg/nw_mvp_23'
  UCSF:
    ground_truth: '/home/carlos/Documentos/proyectos/AUDIT/datasets/ucsf/ucsf_images'
    mvp_1: '/home/carlos/Documentos/proyectos/AUDIT/datasets/ucsf/ucsf_seg/ucsf_mvp_1'
    mvp_2: '/home/carlos/Documentos/proyectos/AUDIT/datasets/ucsf/ucsf_seg/ucsf_mvp_2'
    mvp_2.3: '/home/carlos/Documentos/proyectos/AUDIT/datasets/ucsf/ucsf_seg/ucsf_mvp_23'

model_performance_analysis:
  features:
    NW: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_NW.csv'
    UCSF: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_UCSF.csv'
  metrics:
    NW: '/home/carlos/Documentos/proyectos/AUDIT/outputs/metrics/extracted_information_NW.csv'
    UCSF: '/home/carlos/Documentos/proyectos/AUDIT/outputs/metrics/extracted_information_UCSF.csv'

model_performance_comparison:
  features:
    NW: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_NW.csv'
    UCSF: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features/extracted_information_UCSF.csv'
  metrics:
    NW: '/home/carlos/Documentos/proyectos/AUDIT/outputs/metrics/extracted_information_NW.csv'
    UCSF: '/home/carlos/Documentos/proyectos/AUDIT/outputs/metrics/extracted_information_UCSF.csv'

longitudinal_measurements:
  features:
    FDA: '/Users/caumente/Projects/robustness/real_datasets_output/features/extracted_information_FDA.csv'
  metrics:
    FDA: '/Users/caumente/Projects/robustness/real_datasets_output/metrics/FDA.csv'

# TODO: Using TOML file
#  TC: 2, 3