feature_extractor_paths:
  NW: '/home/carlos/Documentos/proyectos/AUDIT/datasets/nw/nw_images'
  UCSF: '/home/carlos/Documentos/proyectos/AUDIT/datasets/ucsf/ucsf_images'
  BRATS: '/home/carlos/Documentos/proyectos/AUDIT/datasets/brats2020/brats2020_images'
longitudinal:
  FDA:
    pattern: "-"
    patient_name: 1
    timepoint: 2
labels:
  BKG: 0
  EDE: 2
  ENH: 4
  NEC: 1
planes_orientation: ['axial', 'coronal', 'sagittal']
output_path: '/home/carlos/Documentos/proyectos/AUDIT/outputs/features'
