[feature_extractor_paths]
NW = "/home/carlos/Documentos/proyectos/AUDIT/datasets/nw/nw_images"
UCSF = "/home/carlos/Documentos/proyectos/AUDIT/datasets/ucsf/ucsf_images"
BRATS = "/home/carlos/Documentos/proyectos/AUDIT/datasets/brats2020/brats2020_images"

[longitudinal.FDA]
pattern = "-"
longitudinal_id = 1
time_point = 2

[longitudinal.NW]
pattern = "_"
longitudinal_id = 0
time_point = 1

[labels]
BKG = 0
EDE = 2
ENH = 4
NEC = 1

output_path = "/home/carlos/Documentos/proyectos/AUDIT/outputs/features"