# Path to the raw dataset
data_path: '/home/user/AUDIT/datasets/BraTS2024_SSA/BraTS2024_SSA_seg'

# Paths to model predictions
model_predictions_paths:
  nnUnet: '/home/user/AUDIT/datasets/BraTS2024_SSA/BraTS2024_SSA_seg/nnUnet'
  SegResNet: '/home/user/AUDIT/datasets/BraTS2024_SSA/BraTS2024_SSA_seg/SegResNet'

# Mapping of labels to their numeric values
labels:
  BKG: 0
  EDE: 3
  ENH: 1
  NEC: 2

# List of metrics to compute
metrics:
  dice: true
  jacc: true
  accu: true
  prec: true
  sens: true
  spec: true
  haus: true
  size: true

# Library used for computing all the metrics
package: custom
calculate_stats: false

# Path where output metrics will be saved
output_path: '/home/user/AUDIT/outputs/metrics'

# Filename for the extracted information
filename: 'BraTS2024_SSA'

