# Path to the raw dataset
data_path: '/home/usr/AUDIT/datasets/LUMIERE/LUMIERE_images'

# Paths to model predictions
model_predictions_paths:
  nnUnet: '/home/usr/AUDIT/datasets/LUMIERE/LUMIERE_seg/nnUnet'
  SegResNet: '/home/usr/AUDIT/datasets/LUMIERE/LUMIERE_seg/SegResNet'

# Mapping of labels to their numeric values
labels:
  BKG: 0
  EDE: 3
  ENH: 1
  NEC: 2

# List of metrics to compute
metrics:
  dice: true
  jacc: true
  accu: true
  prec: true
  sens: true
  spec: true
  haus: true
  size: true

# Library used for computing all the metrics
package: audit

# Path where output metrics will be saved
output_path: '/home/usr/AUDIT/outputs/metrics'
filename: 'LUMIERE'
logs_path: '/home/usr/AUDIT/logs/metric'

# others
cpu_cores: 1