# Path to the raw dataset
data_path: '/home/c062o/Documents/projects/AUDIT/datasets/BraTS2024_PED/BraTS2024_PED_images'

# Paths to model predictions
model_predictions_paths:
  nnUnet: '/home/c062o/Documents/projects/AUDIT/datasets/BraTS2024_PED/BraTS2024_PED_seg/nnUnet'
  SegResNet: '/home/c062o/Documents/projects/AUDIT/datasets/BraTS2024_PED/BraTS2024_PED_seg/SegResNet'

# Mapping of labels to their numeric values
labels:
  BKG: 0
  EDE: 3
  ENH: 1
  NEC: 2

# List of metrics to compute
metrics:
  dice: true
  jacc: true
  accu: true
  prec: true
  sens: true
  spec: true
  haus: true
  fbeta: true
  assd: true
  masd: true
  size: true

# Library used for computing all the metrics
package: audit

# Path where output metrics will be saved
output_path: '/home/c062o/Documents/projects/AUDIT/outputs/metrics'
filename: 'BraTS2024_PED'
logs_path: '/home/c062o/Documents/projects/AUDIT/logs/metric'

# others
cpu_cores: 12