class Metrics:
    def __init__(self):
        self.metrics = {
            # AUDIT backend
            "Dice": "DICE",
            "Hausdorff distance": "HAUS",
            "Jaccard": "JACC",
            "Accuracy": "ACCU",
            "Precision": "PREC",
            "Specificity": "SPEC",
            "Sensitivity": "SENS",
            # metrics reloaded backend
            "Number of reference pixels": "numb_ref",
            "Number of predicted pixels": "numb_pred",
            "True positives": "numb_tp",
            "False positives": "numb_fp",
            "False negatives": "numb_fn",
            "Accuracy ": "accuracy",
            "Net Benefit": "nb",
            "Expected Cost": "ec",
            "Balanced Accuracy": "ba",
            "Cohen's kappa": "cohens_kappa",
            "Weighted Cohen's Kappa": "wck",
            "Positive Likelihood ratio +": "lr+",
            "Intersection over Union": "iou",
            "F-beta score": "fbeta",
            "Dice Score Coefficient": "dsc",
            "Matthews Correlation Coefficient": "mcc",
            "CL Dice": "cldice",
            "Average Symmetric Surface Distance": "assd",
            "Boundary IoU": "boundary_iou",
            "Hausdorff dist.": "hd",
            "Hausdorff dist. percentile": "hd_perc",
            "Mean Absolute Surface Distance": "masd",
            "Normalized Surface Distance": "nsd",
            "Positive Predictive Value": "ppv",
            "Negative Predictive Value": "npv",
            "Intersection over Reference": "ior",
            "Sensitivity (Recall)": "sensitivity",
            "Specificity ": "specificity",
            "Absolute Volume Difference Ratio": "avdr",
            # PyMIA backend
            "Adjusted Rand Index": "ari",
            "Area Under Curve": "auc",
            "Average Distance": "avd",
            "Coefficient of Determination": "cd",
            "Cohen Kappa Coefficient": "ckc",
            "Dice Coefficient": "dice",
            "F-Measure": "fmeas",
            "Fallout": "fallout",
            "False Negative": "fn",
            "False Negative Rate": "fnr",
            "False Positive": "fp",
            "Global Consistency Error": "gce",
            "Hausdorff Distance": "haus",
            "Interclass Correlation": "ic",
            "Jaccard Coefficient": "jacc",
            "Mahalanobis Distance": "mahal",
            "Mean Absolute Error": "mae",
            "Mean Squared Error": "mse",
            "Mutual Information": "mi",
            "Normalized Root Mean Squared Error": "nrmse",
            "Predicted Volume": "pred_vol",
            "Probabilistic Distance": "prob",
            "Rand Index": "rand",
            "Reference Volume": "ref_vol",
            "Root Mean Squared Error": "rmse",
            "Surface Dice Overlap": "sdo",
            "Surface Overlap": "so",
            "True Negative": "tn",
            "True Positive": "tp",
            "Variation of Information": "vi",
            "Volume Similarity": "vs",
        }

        self.orderby = {"Ascending": True, "Descending": False}

    def get_metrics(self):
        return self.metrics
